apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: raycluster-javi
spec:
  rayVersion: '2.9.3'
  headGroupSpec:
    rayStartParams:
      dashboard-host: '0.0.0.0'
    template:
      spec:
        containers:
        - name: ray-head
          image: javierqt26/ray_py311_requirements
          ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          resources:
            limits:
              cpu: "3"
              memory: "5G"
            requests:
              cpu: "3"
              memory: "5G"
  workerGroupSpecs:
  - replicas: 19
    groupName: ray-worker
    rayStartParams: {}
    template:
      spec:
        containers:
        - name: ray-worker
          image: javierqt26/ray_py311_requirements
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          resources:
            limits:
              cpu: "3"
              memory: "5G"
            requests:
              cpu: "3"
              memory: "5G"